name = "CommonAppVersions"
uuid = "53be65e0-69d2-464d-8ed9-744df10f6729"
authors = ["Jake Ireland <jakewilliami@icloud.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
VersionParsing = "81def892-9a0e-5fdd-b105-ffc91e053289"

[compat]
AbstractTrees = "0.4.5"
Gumbo = "0.8.2"
HTTP = "1.10.10"
VersionParsing = "1.3.0"
JSON3 = "1.14.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
